### ISSUE TITLE
Images responsive within article main body

### ISSUE THREAD

**Issue by wsmagazine** [washingtonstateuniversity/magazine.wsu.edu#71] opened 2015-09-10 18:29 UTC
I'd like images to have a max-width:100% within the body of articles. Images smaller than that width shouldn't stretch, but larger images would fit better.

**Comment by jeremyfelt** [comment] 2015-10-16 21:15
@wsmagazine Can you provide an example URL for this one?

**Comment by jeremyfelt** [comment] 2015-10-16 21:23
Duplicate of #81

**Closed as completed by jeremyfelt** 2015-10-16 21:23 UTC
